version: '3.4'

services:
  kinderfrontend:
    image: kinderfrontend
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080
