version = 1

[[analyzers]]
name = "docker"
enabled = true

  [analyzers.meta]
  dockerfile_paths = ["/Kinder-Backend"]

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "csharp"
enabled = true